

spring.application.name=ticket

server.port=7070


spring.mvc.view.prefix=/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:postgresql://localhost:5432/avion
spring.datasource.username=postgres
spring.datasource.password=2005


spring.datasource.driver-class-name=org.postgresql.Driver

spring.session.jdbc.initialize-schema=always
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


commission=0.05


spring.jpa.show-sql=true


spring.jpa.properties.hibernate.format_sql=true
